spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:./appdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
